const recipes = {
    'Carne Asada': {
      image: './assets/recipes/recipe-1.jpeg',
      description: 'Succulent grilled beef marinated in citrus and spices, perfect for a hearty dinner.',
      prepTime: '30 min',
      cookTime: '45 min',
      servings: '4 servings',
      tags: ['Dinner', 'Beef', 'Mexican', 'Grill'],
      ingredients: [
        '2 lbs flank steak',
        '1/4 cup lime juice',
        '3 cloves garlic, minced',
        '2 tbsp olive oil',
        '1 tbsp soy sauce',
        '1 tsp ground cumin',
        '1 tsp dried oregano',
        '1/2 tsp chili powder',
        'Salt and pepper to taste',
        '1/4 cup chopped cilantro'
      ],
      tools: [
        'Grill',
        'Meat Thermometer',
        'Cutting Board',
        'Knife',
        'Shallow Dish for Marinating',
        'Tongs'
      ],
      instructions: [
        'Combine lime juice, garlic, olive oil, soy sauce, cumin, oregano, chili powder, salt, and pepper in a bowl.',
        'Place steak in a shallow dish and pour marinade over it. Cover and refrigerate for at least 2 hours, up to 24 hours for best flavor.',
        'Preheat grill to high heat (450-500°F).',
        'Remove steak from marinade and pat dry with paper towels.',
        'Grill steak for 4-5 minutes per side for medium-rare (internal temperature of 135°F).',
        'Let rest for 10 minutes before slicing against the grain.',
        'Sprinkle with fresh cilantro before serving.'
      ]
    },
    'Greek Ribs': {
            image: './assets/recipes/recipe-2.jpeg',
            description: 'Tender pork ribs seasoned with Mediterranean herbs and spices for a delicious Greek-inspired meal.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Pork', 'Greek', 'Baked'],
            ingredients: [
              '2 racks of pork ribs (about 4-5 lbs)',
              '2 tbsp dried oregano',
              '1 tbsp garlic powder',
              '1 tbsp dried thyme',
              '1 tbsp dried rosemary',
              '1 tbsp paprika',
              '1/4 cup olive oil',
              '2 lemons, juiced',
              '1 tbsp honey',
              '2 tsp salt',
              '1 tsp black pepper'
            ],
            tools: [
              'Oven',
              'Baking Tray',
              'Aluminum Foil',
              'Meat Brush',
              'Small Bowl',
              'Measuring Spoons',
              'Kitchen Scissors'
            ],
            instructions: [
              'Preheat oven to 300°F (150°C).',
              'Remove membrane from back of ribs by sliding a knife under it and pulling it off with a paper towel.',
              'In a small bowl, mix oregano, garlic powder, thyme, rosemary, paprika, salt, and pepper.',
              'In another bowl, whisk together olive oil, lemon juice, and honey.',
              'Rub dry herb mixture all over ribs, then brush with oil and lemon mixture.',
              'Wrap ribs tightly in aluminum foil and place on baking tray.',
              'Bake for 2 hours or until meat is tender and pulling away from bones.',
              'Unwrap ribs, increase oven temperature to 425°F (220°C).',
              'Brush ribs with remaining oil mixture and return to oven for 15-20 minutes until slightly crisp.',
              'Let rest for 10 minutes before cutting and serving.'
            ]
          },
          'Vegetable Soup': {
            image: './assets/recipes/recipe-3.jpeg',
            description: 'A hearty and nutritious soup packed with fresh seasonal vegetables and aromatic herbs.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Lunch', 'Vegan', 'Soup', 'Healthy'],
            ingredients: [
              '2 tbsp olive oil',
              '1 large onion, diced',
              '3 cloves garlic, minced',
              '2 carrots, peeled and chopped',
              '2 celery stalks, diced',
              '1 red bell pepper, chopped',
              '1 zucchini, diced',
              '1 cup green beans, trimmed and cut',
              '1 cup frozen peas',
              '1 can (14 oz) diced tomatoes',
              '4 cups vegetable broth',
              '2 bay leaves',
              '1 tsp dried thyme',
              '1/2 tsp dried rosemary',
              '1 tsp salt, or to taste',
              '1/2 tsp black pepper',
              '2 tbsp fresh parsley, chopped',
              '1 tbsp lemon juice'
            ],
            tools: [
              'Large Pot',
              'Cutting Board',
              'Chef\'s Knife',
              'Wooden Spoon',
              'Measuring Cups and Spoons',
              'Vegetable Peeler',
              'Ladle'
            ],
            instructions: [
              'Heat olive oil in a large pot over medium heat.',
              'Add onions and sauté for 3-4 minutes until translucent.',
              'Add garlic and cook for another minute until fragrant.',
              'Add carrots and celery, cook for 5 minutes, stirring occasionally.',
              'Add bell pepper, zucchini, and green beans, cook for 3 minutes.',
              'Pour in diced tomatoes and vegetable broth.',
              'Add bay leaves, thyme, rosemary, salt, and pepper.',
              'Bring to a boil, then reduce heat and simmer for 20 minutes.',
              'Add frozen peas and simmer for another 5 minutes.',
              'Remove bay leaves, stir in fresh parsley and lemon juice.',
              'Adjust seasoning if needed and serve hot.'
            ]
          },
          'Banana Pancakes': {
            image: './assets/recipes/recipe-4.jpeg',
            description: 'Fluffy pancakes with ripe bananas, perfect for a weekend breakfast or brunch. Sweet, satisfying, and kid-friendly.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Breakfast', 'Sweet', 'Vegetarian', 'Kid-Friendly'],
            ingredients: [
              '1 1/2 cups all-purpose flour',
              '2 tbsp sugar',
              '2 tsp baking powder',
              '1/2 tsp cinnamon',
              '1/4 tsp salt',
              '2 ripe bananas, mashed (plus additional sliced banana for topping)',
              '1 cup milk',
              '2 large eggs',
              '1 tsp vanilla extract',
              '2 tbsp melted butter (plus more for cooking)',
              'Maple syrup for serving',
              'Optional toppings: chopped walnuts, chocolate chips'
            ],
            tools: [
              'Mixing Bowls',
              'Whisk',
              'Non-stick Skillet or Griddle',
              'Spatula',
              'Measuring Cups and Spoons',
              'Fork for Mashing',
              'Ladle or 1/4 Cup Measure'
            ],
            instructions: [
              'In a large bowl, whisk together flour, sugar, baking powder, cinnamon, and salt.',
              'In another bowl, mash bananas thoroughly with a fork.',
              'Add milk, eggs, vanilla extract, and melted butter to the mashed bananas and mix well.',
              'Pour wet ingredients into dry ingredients and stir just until combined (small lumps are okay).',
              'Heat a skillet or griddle over medium heat and lightly coat with butter.',
              'Pour 1/4 cup batter for each pancake onto the hot surface.',
              'Cook until bubbles form on top and edges appear set (about 2-3 minutes).',
              'Flip and cook until golden brown on the other side (about 1-2 minutes).',
              'Serve warm with maple syrup, sliced bananas, and optional toppings.'
            ]
          },
          'Spicy Tuna Bowl': {
            image: './assets/recipes/recipe-5.jpeg',
            description: 'Fresh tuna with a spicy kick, served over seasoned rice with avocado and vegetables for a quick and healthy meal.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Lunch', 'Seafood', 'Asian', 'Healthy'],
            ingredients: [
              '1/2 lb sushi-grade tuna, diced',
              '1 cup sushi rice',
              '1 1/2 cups water',
              '2 tbsp rice vinegar',
              '1 tsp sugar',
              '1/2 tsp salt',
              '2 tbsp sriracha sauce',
              '1 tbsp soy sauce',
              '1 tsp sesame oil',
              '1 ripe avocado, sliced',
              '1/2 cucumber, thinly sliced',
              '2 radishes, thinly sliced',
              '1 green onion, chopped',
              '1 sheet nori, cut into strips',
              '1 tbsp toasted sesame seeds',
              'Optional: wasabi and pickled ginger for serving'
            ],
            tools: [
              'Rice Cooker or Medium Pot',
              'Sharp Knife',
              'Cutting Board',
              'Small Bowls',
              'Measuring Cups and Spoons',
              'Mixing Bowl'
            ],
            instructions: [
              'Rinse sushi rice until water runs clear, then cook according to package instructions.',
              'In a small bowl, mix rice vinegar, sugar, and salt. Fold into hot cooked rice.',
              'In another bowl, combine sriracha, soy sauce, and sesame oil.',
              'Dice tuna into small cubes and gently mix with half of the sriracha sauce mixture.',
              'Divide seasoned rice between two bowls.',
              'Top rice with spicy tuna, sliced avocado, cucumber, and radishes.',
              'Drizzle remaining sauce over the bowls.',
              'Garnish with green onion, nori strips, and sesame seeds.',
              'Serve immediately with optional wasabi and pickled ginger on the side.'
            ]
          },
          'Chocolate Lava Cake': {
            image: './assets/recipes/recipe-6.jpeg',
            description: 'Decadent individual chocolate cakes with a molten chocolate center. A perfect impressive dessert that\'s surprisingly easy to make.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dessert', 'Chocolate', 'Baking', 'Special Occasion'],
            ingredients: [
              '1/2 cup (1 stick) unsalted butter, plus more for greasing',
              '4 oz high-quality dark chocolate (70% cocoa)',
              '2 large eggs',
              '2 large egg yolks',
              '1/4 cup granulated sugar',
              '1 tsp vanilla extract',
              'Pinch of salt',
              '2 tbsp all-purpose flour',
              '1 tbsp unsweetened cocoa powder',
              'Powdered sugar for dusting',
              'Optional: vanilla ice cream or whipped cream for serving',
              'Optional: fresh berries for garnish'
            ],
            tools: [
              'Microwave or Double Boiler',
              'Mixing Bowl',
              '4 (6-oz) Ramekins',
              'Whisk',
              'Spatula',
              'Baking Sheet',
              'Sifter for Powdered Sugar'
            ],
            instructions: [
              'Preheat oven to 425°F (220°C). Butter and lightly flour ramekins.',
              'Chop chocolate into small pieces. In microwave-safe bowl, combine butter and chocolate.',
              'Microwave in 30-second intervals, stirring between each, until fully melted and smooth.',
              'In a separate bowl, whisk together eggs, egg yolks, sugar, vanilla, and salt until light and frothy.',
              'Slowly fold chocolate mixture into egg mixture until combined.',
              'Gently fold in flour and cocoa powder until just incorporated (don\'t overmix).',
              'Divide batter evenly among prepared ramekins.',
              'Place ramekins on a baking sheet and bake for 12-14 minutes until edges are firm but centers are soft.',
              'Let stand for 1 minute, then run a knife around edges and invert onto serving plates.',
              'Dust with powdered sugar and serve immediately with ice cream and berries if desired.'
            ]
          },
          'Classic Chicken Adobo': {
            image: './assets/recipes/adobo.jpg',
            description: 'A classic Filipino dish of chicken braised in vinegar, soy sauce, and garlic. A staple in Filipino cuisine known for its tangy and savory flavor that improves overnight.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Filipino', 'Chicken', 'One-Pot'],
            ingredients: [
              '2 lbs chicken pieces (thighs and drumsticks work best)',
              '1/2 cup white vinegar',
              '1/2 cup soy sauce',
              '1 cup water',
              '1 head garlic (about 10-12 cloves), minced',
              '1 large onion, sliced',
              '2 bay leaves',
              '1 tbsp whole black peppercorns',
              '1 tbsp brown sugar (optional)',
              '2 tbsp cooking oil',
              '3 green onions, chopped (for garnish)',
              'Steamed rice, for serving'
            ],
            tools: [
              'Large Heavy-Bottomed Pot or Dutch Oven',
              'Wooden Spoon',
              'Cutting Board',
              'Knife',
              'Measuring Cups and Spoons',
              'Tongs'
            ],
            instructions: [
              'In a large pot, heat oil over medium heat. Add garlic and onion, sauté until fragrant and onions are translucent.',
              'Add chicken pieces and brown on all sides, about 5 minutes.',
              'Pour in vinegar and allow to simmer for 2 minutes without stirring (this prevents the vinegar from becoming too bitter).',
              'Add soy sauce, water, bay leaves, peppercorns, and brown sugar if using.',
              'Bring to a boil, then reduce heat to low. Cover and simmer for 35-40 minutes or until chicken is tender and fully cooked.',
              'For a thicker sauce, remove chicken and boil the sauce uncovered until reduced to desired consistency.',
              'Return chicken to the pot to warm through if needed.',
              'Remove bay leaves before serving.',
              'Serve hot over steamed rice, garnished with green onions.'
            ]
          },
          'Tangy Pork Sinigang': {
            image: './assets/recipes/sinigang.jpg',
            description: 'A popular Filipino sour soup made with pork and various vegetables, characterized by its distinctive tangy tamarind flavor. Perfect for rainy days and cold weather.',
            prepTime: '25 min',
            cookTime: '1 hour 15 min',
            servings: '6 servings',
            tags: ['Lunch', 'Filipino', 'Soup', 'Pork'],
            ingredients: [
              '2 lbs pork belly or pork ribs, cut into 2-inch pieces',
              '1 large onion, quartered',
              '2 tomatoes, quartered',
              '1 pack (40-50g) sinigang mix or 2 tbsp tamarind paste',
              '8 cups water',
              '2 green chili peppers (siling haba)',
              '1 radish (labanos), peeled and sliced',
              '1 medium eggplant, sliced',
              '2 pieces taro (gabi), peeled and quartered',
              '10 string beans (sitaw), cut into 2-inch pieces',
              '2 cups water spinach (kangkong), leaves and tender stalks',
              '2 tbsp fish sauce (patis)',
              'Salt to taste'
            ],
            tools: [
              'Large Pot',
              'Cutting Board',
              'Knife',
              'Ladle',
              'Measuring Cups and Spoons',
              'Vegetable Peeler',
              'Skimmer'
            ],
            instructions: [
              'In a large pot, combine pork, onion, tomatoes, and water. Bring to a boil.',
              'Reduce heat and simmer for 45 minutes or until pork is tender, skimming off any foam that rises to the surface.',
              'Add taro and radish, simmer for 5 minutes.',
              'Add sinigang mix or tamarind paste and stir until completely dissolved.',
              'Add eggplant and string beans, cook for 5 minutes.',
              'Add green chili peppers and water spinach, cook for another 2 minutes.',
              'Season with fish sauce and salt to taste.',
              'Remove from heat and let stand for 5 minutes before serving.',
              'Serve hot with steamed rice and a side of fish sauce for dipping the meat.'
            ]
          },
          'Pancit Canton': {
            image: './assets/recipes/pac.jpg',
            description: 'A popular Filipino noodle dish with stir-fried egg noodles, mixed vegetables, and meat, symbolizing long life and good health. A must-have at Filipino celebrations.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Lunch', 'Filipino', 'Noodles', 'Party'],
            ingredients: [
              '1 lb (500g) pancit canton noodles (egg noodles)',
              '1/2 lb chicken breast, thinly sliced',
              '1/4 lb pork belly, thinly sliced',
              '1/2 cup shrimp, peeled and deveined (optional)',
              '4 cloves garlic, minced',
              '1 medium onion, sliced',
              '1 carrot, julienned',
              '1 cup cabbage, shredded',
              '1/2 cup snow peas or snap peas',
              '1/4 cup celery, sliced',
              '3 tbsp soy sauce',
              '2 tbsp oyster sauce',
              '2 cups chicken broth',
              '3 tbsp cooking oil',
              '2-3 calamansi or 1 lemon, cut into wedges',
              '3 stalks green onions, chopped',
              'Ground black pepper to taste'
            ],
            tools: [
              'Wok or Large Skillet',
              'Spatula',
              'Cutting Board',
              'Knife',
              'Tongs',
              'Large Bowl for Soaking Noodles',
              'Measuring Cups and Spoons'
            ],
            instructions: [
              'Soak dried pancit canton noodles in warm water for 10 minutes, then drain.',
              'Heat oil in a wok or large skillet over medium-high heat.',
              'Sauté garlic and onion until fragrant and onions are translucent.',
              'Add chicken and pork, cook until browned and nearly cooked through.',
              'Add shrimp if using, and cook until they turn pink.',
              'Add carrots, cabbage, snow peas, and celery. Stir-fry for 2-3 minutes.',
              'Pour in chicken broth, soy sauce, and oyster sauce. Bring to a simmer.',
              'Add noodles to the wok and toss until they absorb the sauce and are cooked through (about 5-7 minutes).',
              'Season with black pepper to taste.',
              'Garnish with green onions before serving.',
              'Serve hot with calamansi or lemon wedges on the side for squeezing over the noodles.'
            ]
          },
          'Lumpia Shanghai': {
            image: './assets/recipes/lumpia.jpg',
            description: 'Crispy Filipino spring rolls filled with seasoned ground meat and vegetables, typically served as a popular appetizer or snack with a sweet and sour dipping sauce.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Appetizer', 'Filipino', 'Party Food', 'Fried'],
            ingredients: [
              '1 lb ground pork',
              '1/4 lb shrimp, finely chopped (optional)',
              '1/2 cup onions, finely chopped',
              '1/4 cup carrots, finely minced',
              '1/4 cup celery, finely minced',
              '3 cloves garlic, minced',
              '2 eggs',
              '2 tbsp soy sauce',
              '1 tsp salt',
              '1/2 tsp ground black pepper',
              '1 tsp garlic powder',
              '50 lumpia wrappers (spring roll wrappers)',
              '1 egg white, beaten (for sealing)',
              '4 cups oil for frying',
              'Sweet and sour sauce or banana ketchup for dipping'
            ],
            tools: [
              'Large Mixing Bowl',
              'Cutting Board',
              'Knife',
              'Food Processor (optional)',
              'Deep Frying Pan or Wok',
              'Tongs',
              'Paper Towels',
              'Plate or Tray'
            ],
            instructions: [
              'In a large bowl, combine ground pork, shrimp (if using), onions, carrots, celery, garlic, eggs, soy sauce, salt, pepper, and garlic powder. Mix thoroughly.',
              'Place 1-2 tablespoons of filling near the bottom edge of a lumpia wrapper.',
              'Fold the bottom edge over the filling, then fold in the sides. Roll tightly towards the top edge.',
              'Seal the edge with egg white.',
              'Repeat with remaining wrappers and filling.',
              'Heat oil in a deep pan to 350°F (175°C).',
              'Fry lumpia in batches, 5-6 pieces at a time, for 3-4 minutes or until golden brown.',
              'Remove with tongs and drain on paper towels.',
              'Serve hot with sweet and sour sauce or banana ketchup.',
              'Note: Uncooked lumpia can be frozen for later use - just place them in a single layer on a tray, freeze until solid, then transfer to freezer bags.'
            ]
          },
          'Sizzling Pork Sisig': {
            image: './assets/recipes/sisig.jpg',
            description: 'A sizzling Filipino dish made from chopped pork parts, typically served on a hot plate with a tangy and spicy flavor profile. Perfect as an appetizer with beer or as a main dish with rice.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Filipino', 'Pork', 'Spicy', 'Beer Match'],
            ingredients: [
              '1 lb pork belly',
              '1/2 lb pig\'s face (snout, ears, cheeks) or substitute with more pork belly',
              '1/4 lb chicken liver, chopped',
              '1 large onion, finely chopped',
              '3 Thai chili peppers, finely chopped',
              '5 cloves garlic, minced',
              '1/4 cup calamansi juice or 3 tbsp lime juice',
              '3 tbsp soy sauce',
              '3 tbsp vinegar',
              '1/2 tsp black pepper',
              '1 tsp salt',
              '2 tbsp butter',
              '2 tbsp mayonnaise (optional)',
              '1 raw egg (optional, for serving)',
              '3 tbsp cooking oil',
              'Lemon or calamansi wedges for serving'
            ],
            tools: [
              'Grill or Broiler',
              'Large Pot for Boiling',
              'Cutting Board',
              'Sharp Knife',
              'Sizzling Plate or Cast Iron Skillet',
              'Mixing Bowl',
              'Tongs'
            ],
            instructions: [
              'Boil pork belly and pig\'s face in water with salt and pepper for 30 minutes or until tender but not falling apart.',
              'Drain and cool the meat. Grill or broil until slightly charred and crispy on the outside.',
              'Chop all the meat into small, uniform pieces (about 1/4 inch cubes).',
              'In a large pan or wok, heat oil and sauté garlic until fragrant.',
              'Add onions and chili peppers, sauté for 2 minutes.',
              'Add chopped liver and cook for 2-3 minutes.',
              'Add chopped grilled pork, soy sauce, vinegar, and calamansi juice. Cook for 5 minutes.',
              'Season with salt and pepper to taste.',
              'If using a sizzling plate, heat it until very hot. Add butter to the plate and immediately transfer the sisig mixture.',
              'Top with mayonnaise if using and mix quickly.',
              'Optionally, crack a raw egg on top just before serving.',
              'Serve immediately with lemon or calamansi wedges and steamed rice.'
            ]
          },
          'Ube Chiffon Cake': {
            image: './assets/recipes/ube.jpg',
            description: 'A light and fluffy Filipino cake made with ube (purple yam), known for its distinct purple color and unique flavor. Perfect for celebrations and special occasions.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dessert', 'Filipino', 'Baking', 'Special Occasion'],
            ingredients: [
              '2 1/4 cups cake flour',
              '1 tbsp baking powder',
              '1 tsp salt',
              '1 1/2 cups granulated sugar (divided)',
              '7 egg yolks',
              '1/2 cup vegetable oil',
              '3/4 cup milk',
              '1 cup ube halaya (purple yam jam)',
              '1 tsp ube extract or purple food coloring',
              '1 tsp vanilla extract',
              '7 egg whites',
              '1/2 tsp cream of tartar',
              'For the optional glaze:',
              '2 cups powdered sugar',
              '3 tbsp milk',
              '1/2 tsp vanilla extract',
              '1/2 tsp ube extract'
            ],
            tools: [
              'Electric Mixer',
              '10-inch Tube Pan or Angel Food Cake Pan',
              'Mixing Bowls',
              'Sifter',
              'Rubber Spatula',
              'Measuring Cups and Spoons',
              'Wire Rack'
            ],
            instructions: [
              'Preheat oven to 325°F (165°C). Do not grease the tube pan.',
              'In a large bowl, sift together cake flour, baking powder, salt, and 3/4 cup sugar.',
              'In another bowl, whisk egg yolks, oil, milk, ube halaya, ube extract, and vanilla until smooth.',
              'Make a well in the center of the dry ingredients and gradually add the wet mixture. Mix until smooth.',
              'In a separate clean bowl, beat egg whites and cream of tartar until foamy.',
              'Gradually add remaining 3/4 cup sugar and beat until stiff peaks form.',
              'Gently fold egg whites into the ube batter in three additions, being careful not to deflate the mixture.',
              'Pour batter into ungreased tube pan and smooth the top.',
              'Bake for 45-50 minutes or until a toothpick inserted comes out clean.',
              'Immediately invert the pan onto a wire rack and let cool completely (about 2 hours).',
              'Run a knife around the edges to release the cake.',
              'For optional glaze: Whisk together powdered sugar, milk, vanilla, and ube extract until smooth. Drizzle over cooled cake.',
              'Slice and serve. Store covered at room temperature for up to 3 days.'
            ]
          },
          'Chicken Curry': {
            image: './assets/recipes/curry.jpg',
            description: 'A fragrant and creamy Indian-style chicken curry with aromatic spices and tender chicken pieces. Perfect served with rice or naan bread.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Indian', 'Chicken', 'Curry'],
            ingredients: [
              '2 lbs chicken thighs, cut into pieces',
              '2 onions, finely chopped',
              '4 cloves garlic, minced',
              '1 inch ginger, grated',
              '2 tomatoes, chopped',
              '1 cup coconut milk',
              '2 tbsp curry powder',
              '1 tsp turmeric powder',
              '1 tsp cumin powder',
              '1 tsp coriander powder',
              '2 tbsp vegetable oil',
              '1 cinnamon stick',
              '2 cardamom pods',
              '2 bay leaves',
              'Salt to taste',
              'Fresh cilantro for garnish'
            ],
            tools: [
              'Large Heavy-Bottomed Pan',
              'Cutting Board',
              'Knife',
              'Measuring Spoons',
              'Wooden Spoon',
              'Grater'
            ],
            instructions: [
              'Heat oil in a large pan over medium heat. Add cinnamon, cardamom, and bay leaves.',
              'Add onions and sauté until golden brown.',
              'Add garlic and ginger, cook for 1 minute until fragrant.',
              'Add chicken pieces and cook until they change color.',
              'Add curry powder, turmeric, cumin, and coriander. Stir well.',
              'Add tomatoes and cook until they soften.',
              'Pour in coconut milk and bring to a simmer.',
              'Cover and cook for 25-30 minutes until chicken is tender.',
              'Season with salt to taste.',
              'Garnish with fresh cilantro before serving.'
            ]
          },
          'Beef Stir Fry': {
            image: './assets/recipes/stirfry.jpg',
            description: 'Quick and flavorful beef stir fry with colorful vegetables in a savory sauce. A perfect weeknight dinner that comes together in minutes.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Asian', 'Beef', 'Quick'],
            ingredients: [
              '1 lb beef sirloin, thinly sliced',
              '2 bell peppers, sliced',
              '1 broccoli head, cut into florets',
              '2 carrots, julienned',
              '4 cloves garlic, minced',
              '1 inch ginger, grated',
              '3 tbsp soy sauce',
              '2 tbsp oyster sauce',
              '1 tbsp cornstarch',
              '2 tbsp vegetable oil',
              '1 tsp sesame oil',
              '2 green onions, sliced',
              'Sesame seeds for garnish'
            ],
            tools: [
              'Wok or Large Skillet',
              'Cutting Board',
              'Knife',
              'Measuring Spoons',
              'Small Bowl for Sauce',
              'Tongs'
            ],
            instructions: [
              'Mix soy sauce, oyster sauce, and cornstarch in a small bowl.',
              'Heat vegetable oil in a wok or large skillet over high heat.',
              'Add beef and stir-fry until browned, about 2-3 minutes. Remove and set aside.',
              'Add garlic and ginger, stir for 30 seconds.',
              'Add vegetables and stir-fry for 3-4 minutes until crisp-tender.',
              'Return beef to the pan.',
              'Pour sauce mixture over and stir until thickened.',
              'Drizzle with sesame oil and garnish with green onions and sesame seeds.',
              'Serve hot with rice.'
            ]
          },
          'Mediterranean Salad': {
            image: './assets/recipes/medsalad.jpg',
            description: 'A refreshing and healthy Mediterranean salad with fresh vegetables, feta cheese, and olives. Perfect for lunch or as a side dish.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Lunch', 'Vegetarian', 'Salad', 'Healthy'],
            ingredients: [
              '1 cucumber, diced',
              '2 tomatoes, diced',
              '1 red onion, thinly sliced',
              '1 bell pepper, diced',
              '1 cup Kalamata olives',
              '200g feta cheese, cubed',
              '1/4 cup extra virgin olive oil',
              '2 tbsp red wine vinegar',
              '1 tsp dried oregano',
              '1/2 tsp salt',
              '1/4 tsp black pepper',
              'Fresh parsley, chopped'
            ],
            tools: [
              'Large Mixing Bowl',
              'Cutting Board',
              'Knife',
              'Measuring Cups and Spoons',
              'Small Bowl for Dressing',
              'Whisk'
            ],
            instructions: [
              'Combine cucumber, tomatoes, onion, bell pepper, olives, and feta in a large bowl.',
              'In a small bowl, whisk together olive oil, vinegar, oregano, salt, and pepper.',
              'Pour dressing over salad and toss gently.',
              'Garnish with fresh parsley.',
              'Serve immediately or refrigerate for up to 2 hours before serving.'
            ]
          },
          'Chocolate Chip Cookies': {
            image: './assets/recipes/cookies.jpeg',
            description: 'Classic homemade chocolate chip cookies with a perfect balance of crispy edges and chewy centers. A timeless treat for any occasion.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dessert', 'Baking', 'Sweet', 'Kid-Friendly'],
            ingredients: [
              '2 1/4 cups all-purpose flour',
              '1 tsp baking soda',
              '1 tsp salt',
              '1 cup (2 sticks) butter, softened',
              '3/4 cup granulated sugar',
              '3/4 cup brown sugar',
              '2 large eggs',
              '2 tsp vanilla extract',
              '2 cups chocolate chips',
              '1 cup chopped walnuts (optional)'
            ],
            tools: [
              'Electric Mixer',
              'Mixing Bowls',
              'Measuring Cups and Spoons',
              'Baking Sheets',
              'Parchment Paper',
              'Cookie Scoop',
              'Wire Rack'
            ],
            instructions: [
              'Preheat oven to 375°F (190°C).',
              'Mix flour, baking soda, and salt in a small bowl.',
              'Beat butter, granulated sugar, and brown sugar until creamy.',
              'Add eggs and vanilla, beat well.',
              'Gradually mix in flour mixture.',
              'Stir in chocolate chips and walnuts if using.',
              'Drop rounded tablespoons of dough onto ungreased baking sheets.',
              'Bake for 9-11 minutes or until golden brown.',
              'Cool on baking sheets for 2 minutes, then remove to wire racks.',
              'Store in airtight container.'
            ]
          },
          'Vegetable Lasagna': {
            image: './assets/recipes/lasagna.jpg',
            description: 'A hearty vegetarian lasagna layered with fresh vegetables, rich tomato sauce, and creamy cheese. A satisfying meatless main dish.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Vegetarian', 'Italian', 'Baked'],
            ingredients: [
              '12 lasagna noodles',
              '2 cups ricotta cheese',
              '2 cups shredded mozzarella',
              '1/2 cup grated Parmesan',
              '2 cups marinara sauce',
              '2 zucchini, sliced',
              '2 yellow squash, sliced',
              '1 eggplant, sliced',
              '2 cups spinach',
              '4 cloves garlic, minced',
              '1 onion, diced',
              '2 tbsp olive oil',
              '1 tsp dried basil',
              '1 tsp dried oregano',
              'Salt and pepper to taste'
            ],
            tools: [
              '9x13 Baking Dish',
              'Large Pot',
              'Skillet',
              'Cutting Board',
              'Knife',
              'Mixing Bowls',
              'Measuring Cups and Spoons'
            ],
            instructions: [
              'Preheat oven to 375°F (190°C).',
              'Cook lasagna noodles according to package directions.',
              'Heat oil in skillet and sauté onion and garlic until soft.',
              'Add vegetables and cook until tender.',
              'Mix ricotta, 1 cup mozzarella, and Parmesan in a bowl.',
              'Spread 1/2 cup marinara in bottom of baking dish.',
              'Layer noodles, ricotta mixture, vegetables, and sauce.',
              'Repeat layers, ending with sauce and remaining mozzarella.',
              'Cover with foil and bake for 30 minutes.',
              'Remove foil and bake 15 minutes more until bubbly.',
              'Let stand 10 minutes before serving.'
            ]
          },
          'Avocado Toast': {
            image: './assets/recipes/avocado-toast.jpeg',
            description: 'A simple yet delicious breakfast staple featuring creamy avocado on toasted bread, topped with various seasonings and optional toppings.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Breakfast', 'Vegan', 'Quick', 'Healthy'],
            ingredients: [
              '2 slices of sourdough or whole grain bread',
              '1 ripe avocado',
              '1 tbsp lemon juice',
              '1/4 tsp red pepper flakes',
              'Salt and pepper to taste',
              '2 tbsp extra virgin olive oil',
              'Optional toppings:',
              '2 eggs (poached or fried)',
              'Microgreens or sprouts',
              'Everything bagel seasoning',
              'Feta cheese crumbles',
              'Cherry tomatoes, halved'
            ],
            tools: [
              'Toaster',
              'Small Bowl',
              'Fork',
              'Knife',
              'Cutting Board'
            ],
            instructions: [
              'Toast bread until golden and crispy.',
              'Mash avocado with lemon juice, salt, and pepper.',
              'Spread avocado on toast and drizzle with olive oil.',
              'Add red pepper flakes and optional toppings.',
              'Serve immediately while warm.'
            ]
          },
          'Bibingka': {
            image: './assets/recipes/bibingka.jpg',
            description: 'A traditional Filipino rice cake made with rice flour and coconut milk, traditionally cooked in clay pots lined with banana leaves. Perfect for breakfast or merienda (afternoon snack).',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dessert', 'Filipino', 'Breakfast', 'Traditional'],
            ingredients: [
              '2 cups rice flour',
              '1 cup all-purpose flour',
              '1 cup granulated sugar',
              '2 tbsp baking powder',
              '1/2 tsp salt',
              '3 eggs',
              '1 1/2 cups coconut milk',
              '1/2 cup evaporated milk',
              '1/4 cup melted butter',
              'Banana leaves (for lining)',
              'Salted eggs, sliced (optional)',
              'Grated cheese (optional)',
              'Butter for brushing',
              'Sugar for sprinkling'
            ],
            tools: [
              'Mixing Bowls',
              'Whisk',
              'Baking Pans',
              'Oven',
              'Brush'
            ],
            instructions: [
              'Preheat oven to 350°F and line pans with banana leaves.',
              'Mix dry ingredients: rice flour, all-purpose flour, sugar, baking powder, and salt.',
              'Combine wet ingredients: eggs, coconut milk, evaporated milk, and butter.',
              'Mix wet and dry ingredients until smooth.',
              'Pour into pans and top with salted eggs and cheese if using.',
              'Bake for 20-25 minutes until done.',
              'Brush with butter and sprinkle with sugar.',
              'Serve warm.'
            ]
          },
          'Grilled Salmon': {
            image: './assets/recipes/salmon.jpeg',
            description: 'Perfectly grilled salmon fillets with a crispy skin and tender, flaky flesh. A healthy and delicious main course that\'s quick to prepare.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Seafood', 'Healthy', 'Grill'],
            ingredients: [
              '4 salmon fillets (6-8 oz each)',
              '2 tbsp olive oil',
              '2 cloves garlic, minced',
              '1 lemon, juiced and zested',
              '1 tbsp fresh dill, chopped',
              '1 tsp paprika',
              'Salt and pepper to taste',
              'Lemon wedges for serving',
              'Fresh herbs for garnish'
            ],
            tools: [
              'Grill',
              'Fish Spatula',
              'Mixing Bowl',
              'Brush',
              'Zester'
            ],
            instructions: [
              'Preheat grill to medium-high heat.',
              'Pat salmon dry and mix oil, garlic, lemon, dill, paprika, salt, and pepper.',
              'Brush mixture over salmon fillets.',
              'Grill skin-side up for 4-5 minutes, then flip.',
              'Grill another 4-5 minutes until cooked through.',
              'Rest for 2-3 minutes and serve with lemon wedges.'
            ]
          },
          'Arroz Caldo': {
            image: './assets/recipes/arroz-caldo.jpg',
            description: 'A comforting Filipino rice porridge with chicken, ginger, and garlic. Often served during cold weather or when someone is feeling under the weather.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Breakfast', 'Filipino', 'Soup', 'Comfort Food'],
            ingredients: [
              '2 cups glutinous rice (malagkit)',
              '1 lb chicken, cut into pieces',
              '1 thumb ginger, julienned',
              '6 cloves garlic, minced',
              '1 large onion, diced',
              '8 cups chicken broth',
              '2 tbsp fish sauce (patis)',
              '1/4 tsp safflower (kasubha) or turmeric powder',
              '2 hard-boiled eggs, sliced',
              '2 green onions, chopped',
              '1/4 cup fried garlic',
              'Calamansi or lemon wedges',
              'Salt and pepper to taste'
            ],
            tools: [
              'Large Pot',
              'Wooden Spoon',
              'Cutting Board',
              'Knife',
              'Ladle'
            ],
            instructions: [
              'Rinse rice and drain.',
              'Sauté garlic, onion, and ginger until fragrant.',
              'Add chicken and cook until browned.',
              'Add rice and stir for 2-3 minutes.',
              'Pour in broth and simmer for 30-35 minutes.',
              'Add fish sauce and safflower/turmeric for color.',
              'Season with salt and pepper.',
              'Serve hot with toppings and calamansi wedges.'
            ]
          },
          'Beef Bulalo': {
            image: './assets/recipes/bulalo.jpg',
            description: 'A hearty Filipino soup made with beef shanks and bone marrow, simmered for hours until the meat is tender and the broth is rich and flavorful.',
            prepTime: '30 min',
            cookTime: '45 min',
            servings: '4 servings',
            tags: ['Dinner', 'Filipino', 'Soup', 'Comfort Food'],
            ingredients: [
              '2 lbs beef shanks with bone marrow',
              '1 large onion, quartered',
              '4 cloves garlic, crushed',
              '2 corn cobs, cut into 3-inch pieces',
              '2 pieces cabbage, quartered',
              '2 pieces pechay (bok choy)',
              '2 pieces potatoes, quartered',
              '2 pieces carrots, cut into chunks',
              '1 tbsp whole black peppercorns',
              '2 tbsp fish sauce (patis)',
              'Salt to taste',
              'Water for boiling',
              'Green onions for garnish'
            ],
            tools: [
              'Large Pot',
              'Ladle',
              'Strainer',
              'Cutting Board',
              'Knife'
            ],
            instructions: [
              'Combine beef, onion, garlic, and peppercorns in pot.',
              'Add water to cover and bring to boil.',
              'Simmer for 1.5 hours until meat is tender.',
              'Skim off foam and add corn, simmer 15 minutes.',
              'Add potatoes and carrots, cook 10 minutes.',
              'Add cabbage and pechay, cook 5 minutes.',
              'Season with fish sauce and salt.',
              'Serve hot with rice and green onions.'
            ]
          }
  };